### ISSUE TITLE
Shipment POST request is not working

### ISSUE THREAD

**Issue by SamehNagi** [SamehNagi/ShipLe#11]
Using the Shipment POST request to post the following is not working:
{
    "TripID": 3,
    "UserID": 3,
    "SourceCountry": "1",
    "DestinationCountry": "3",
    "DeliveryDate": "2019-28-02T00:00:00",
    "ShipmentName": "Ielts material",
    "ShipmentNote": "take care!"
}
This exception arise:
MySql.Data.MySqlClient.MySqlException: 'Incorrect datetime value: 'yyyy-MM-dd hh:mm tt' for column 'DeliveryDate' at row 1'

**Comment by AhZidan** [comment]
This bug is now fixed and working fine.
