### ISSUE TITLE
Fields names of Trip class 

### ISSUE THREAD

**Issue by SamehNagi** [SamehNagi/ShipLe#6]
Class names MUST follow the database column names.
Notes: 
1- No underscores.
2- Arival_Date have two r letters.
3- Trips time should be recorded.
4- Weight should be AvailableWeight.
5- Note should be TripNote.
6- Transportation should be TransportationType.

**Comment by AhZidan** [comment]
1- Underscores are removed from DB fields and reflected in code.
2- Arival_Date is renamed to ArrivalDate.
3- Trips Time (Data type changed in the database code implementation)
4- Weight is renamed to AvailableWeight.
5- Note is renamed to TripNote
6- Transportation is renamed to TransportationType.

**Comment by AhZidan** [comment]
Pending Validation
